apiVersion: batch/v1
kind: Job
metadata:
  name: sims-test-playground
spec:
  backoffLimit: 5
  completions: 1
  template:
    metadata:
      labels:
        k8s-app: sims-test-playground
    spec:
      restartPolicy: Never
      containers:
      - name: sims-test-playground
        image: jmlehrer/sims:latest
        command: ["stdbuf", "-i0", "-o0", "-e0", "bash", "-c"]
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        args: ["sleep 1000000"]
        resources:
          limits:
            memory: 100Gi
            cpu: "16"
            # nvidia.com/gpu: "1"
          requests:
            memory: 64Gi
            cpu: "8"
            # nvidia.com/gpu: "1"
        volumeMounts:
        - name: ephemeral
          mountPath: "/data"
      volumes:
      # Ephemeral storage
      - name: ephemeral
        emptyDir: {}
